name: Deploy - Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write   # sin esto, el reusable no puede pedir mas de lo que YO tengo
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: dev
      image-tag: dev
    secrets: inherit
